#pip installl numpy 
import numpy as np

In [2]:
a = np.array([1,2,3,4]) 

In [3]:
print (a)

[1 2 3 4]


In [4]:
b = np.array([[1,2,3,4],[1,2,3,4]])

In [5]:
print (b)

[[1 2 3 4]
 [1 2 3 4]]


In [6]:
a.ndim #dimensions

1

In [7]:
b.ndim #dimensions

2

In [8]:
b.shape # (rows,cols)

(2, 4)

In [53]:
a.dtype #datatype

dtype('int32')

In [55]:
b.dtype

dtype('int32')

In [59]:
b.itemsize

4

In [63]:
a.nbytes

16

In [68]:
b.nbytes

32

In [69]:
s = np.zeros ((2,3)) 

In [70]:
print (s)

[[0. 0. 0.]
 [0. 0. 0.]]


In [71]:
d = np.full((2,3),99)

In [72]:
print (d)

[[99 99 99]
 [99 99 99]]


In [78]:
f = np.full((3,2),99)

In [79]:
print (f)

[[99 99]
 [99 99]
 [99 99]]


In [80]:
g = np.random.rand(2,1)

In [81]:
print (g)

[[0.07857948]
 [0.1464623 ]]


In [82]:
k = np.identity(2)

In [83]:
print (k)

[[1. 0.]
 [0. 1.]]


In [106]:
l = np.array([2,3])
h = l


In [107]:
print (h)

[2 3]


In [108]:
l = np.array([2,3])
l = h


In [117]:
h = l.copy()
print (h)

[2 3]


In [143]:
x = np.array([1,2,3,4])


In [144]:
x = x + 0
print (x)

[1 2 3 4]


In [145]:
 x = x**2
print (x)

[ 1  4  9 16]
